# Generated by Django 4.2.3 on 2023-07-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_date_alter_event_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants_count',
            field=models.IntegerField(default=0),
        ),
    ]
